spring:
  datasource:
    primary:
      type: ${spring.datasource.type}
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.110.12:13306/fgs
      username: root
      password: 5BP7u4MwiS7xkX!U9QcY@b.f
    second:
      type: ${spring.datasource.type}
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.110.12:13306/xianyu
      username: root
      password: 5BP7u4MwiS7xkX!U9QcY@b.f
  redis:
    redisson: |
      clusterServersConfig:
        idleConnectionTimeout: 10000
        connectTimeout: 10000
        timeout: 3000
        retryAttempts: 3
        retryInterval: 1500
        failedSlaveReconnectionInterval: 3000
        failedSlaveCheckInterval: 60000
        password: null
        subscriptionsPerConnection: 5
        clientName: null
        loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
        subscriptionConnectionMinimumIdleSize: 1
        subscriptionConnectionPoolSize: 50
        slaveConnectionMinimumIdleSize: 24
        slaveConnectionPoolSize: 64
        masterConnectionMinimumIdleSize: 24
        masterConnectionPoolSize: 64
        readMode: "SLAVE"
        subscriptionMode: "SLAVE"
        nodeAddresses:
          - "redis://192.168.110.12:7020"
          - "redis://192.168.110.12:7021"
          - "redis://192.168.110.12:7030"
          - "redis://192.168.110.12:7031"
          - "redis://192.168.110.12:7040"
          - "redis://192.168.110.12:7041"
        scanInterval: 1000
        pingConnectionInterval: 30000
        keepAlive: false
        tcpNoDelay: true
      threads: 16
      nettyThreads: 32
      codec: !<org.redisson.codec.Kryo5Codec> {}
      transportMode: "NIO"