spring:
  application:
    name: app
  data:
    redis:
      host: redis.tctx.xyz
      port: 6379
      username:
      password: 123456
      lettuce:
        pool:
          max-active: 50
          min-idle: 5
          enabled: true